package net.mcreator.artinjustice.procedures;

import net.minecraft.world.level.LevelAccessor;

public class RetrieveTodaysNewsProcedure {
	public static String execute(LevelAccessor world, double par) {
		if (par == 0) {
			if (world.dayTime() <= 20000) {
				return "(#0) The Daily Bugle after years of being just an idea in the brilliant mind of JJJ, is finally becoming a real news agency, both on-line and \"on-paper\"! \u00A7o~Daily Bugle, unsigned";
			}
		}
		if (par == 1) {
			return "(#1) The irresponsible, imature, and trouble-causing Spider-Man strikes again! Folks have been saying that he saved some lifes in today's attack, but what you must understand and I have been saying for the last weeks, is that Spiderman causes all the trouble and attract all the villains that later threatens the lifes he saves. The day this country understand that Spiderman, unlike Captain America, America's greatest hero, is a menace to us, will be the day this nation will finally move forward again! \u00A7o~Daily Bugle, JJJ";
		} else if (par == 2) {
			return "(#2) The billionaire playboy Bruce Wayne has gone nuts with his money! This is by far the most risky acquisition in the history of the Wayne Enterprises, Gotham Water Supply and Distribution Company. The reasons behind this act are still unknown, but by now, we will have some hours until the water supplies are restored, after that, enjoy your Wayne Water! \u00A7o~Gotham Gazette, Vicky Vale, Sponsored by Wayne Enterprises.";
		} else if (par == 3) {
			return "(#3) Along the last night, hundreds of people across the Internet have claimed to see a heavily armed man masked with an orange and black mask, running and jumping across skycrapers under the moonlight, the authorities are still investigating, more details will come on the next days. \u00A7oGotham Gazette, Vicky Vale";
		} else if (par == 7) {
			return "(#7) Citizens of America, have you ever got late to your work because a irresponsible hero crashed your train? Or had to take a cold shower in the dark at a summer night because a negligent hero exploded the city electrical systems? And then you tried to suit him, but somehow a blind lawyear made you pay instead of the \"\"hero\"\"? I, J. Jonah Jameson have faced those situations, and thats why we need new heroes, stronger, smarter and better heroes, and that's why I would like to announce to you, the first group of heroes that have an actual legal adress! I'm talking about Vought company, a new association of heroes, true heroes, not irresponsible web-slingers! \u00A7o~Daily Bugle, JJJ, Sponsored by Vought.";
		} else if (par == 14) {
			return "(#14) Tired of reading about politics, terrorists and evil capitalists? I know exactly what you need, I mean, what everyone needs, a good gossip! America manliest superhero, and America most wished redhead are (un)oficially unavailable. Don't believe me? Some leaked photos of the filming set of the new \"Dawn of the Seven\" movie, that were leaked by I can't say who I was, shows Homelander delivering a frenchie kiss on Maeve hotter than his laser vision, and longer than her sword, yes, you readed it right, I can already imagine what the conservatives and moralists will say about their moral guardian having the pleasure to do to Maeve their deepest wishes that they try to hide even on their sleep. But for us, the normal people, as Homelander himself stated, hope is the last to die, and if I was right about the two having some super-adventures together months ago before these leaks, I will probably be right about that most heroes of the Seven don't keep strict relationships for too long, so, who knows if I, or you, or maybe even we, are the next lucky ones to know what pleasure means to a supe. \u00A7o~Cat Grant, Daily Planet, Sponsored by Vought";
		} else if (par == 21) {
			return "(#21) And what I always say? Have I ever been wrong? Steve Lombard is never wrong when talking about two things, sports, and women! I don't know why Steve was never interviewed by a feminine magazine since I'm always right about women! But Steve, \"you're supposed to talk about sports today, what this have to do with women, bleh, bleh, bleh\", wha you, fellow not-so-smart-like-me-the-great-Steve-Lombard-reader must understand, is that A-Train lost another charity run to Misther Marathon because now his focus is his girl, the ex-star of... you-know-what movies, Popclaw, and that's why I say that a woman will always end up with a man career... [Steve Couldn't finish his misogynist speech due to an ad of a new Vought hero] \u00A7o~Steve Lombard, Daily Planet, Sponsored by Vought";
		} else if (par == 30) {
			return "(#30) There is only one thing I hate more than the public enemy Spider-Man, is Far-Right activists. In the way of the Daily Bugle office, I saw a demonstration of... I won't write that, just thinking on that word gives makes my civilian-cense tingle. They were asking for immigrants to go back to their countries, as if we weren't all imigrants too at some point of our family histories. They say that it's the American Way of Life. No it's not. The American dream is not about some sort of fake purity, it's about the pursuit of happiness that this country allows anyone filled with the spirit of hard-work to achieve. This can't be our people, no, our heroes didn't die for that. \u00A7o~Daily Bugle, JJJ";
		} else if (par == 31) {
			return "(#31) And guess what?! I was... right. After hours of hard working investigation, all those demonstrations, and terrorist attacks across the country aren't from our people, atleast, a part isn't. Millions of dollars are being invested on those coward manifestations, but guess what? Actually, the payments are not on dollars, but on gold, emeralds, diamonds, norse reliquaries, rare specimens of exotic animals. In smaller city, people are not reconizing anymore the inhabitants of their neighborhood. The scumbag arrested on those manifestations have firearms that don't even exist, those people aren't legally registered, and their organs are swapped from right to left. More than forty UFOS have been registered in the last ten hours across the east coast. Something very bad it's happening on our country, and you need to be prepared, if this is so bad as it's seems to be, our heroes will be very occupied stopping whatever storm is coming. I'm John Jonah Jameson, an regular american citizen as any other and I am praying to our Lord to protect every good soul on this country. \u00A7o~Daily Bugle, JJJ";
		} else if (par == 32) {
			return "(#32) We can't start todays news without renembering the thousands of victims of those cruel bastards that are invading our earth. People are being tortured, and murdered, just for being who they are, or standing against the Satanic Sauerkraut-Eaters for those who can't. But today, is a great day, Stormfront, the strongest of the invaders, was beaten to death by a local hero. We know, he is only one of them, but every single time that one of these devils ends up biting the dust, it's a step forward the peace, thus a victory that must be celebrated. \u00A7o~Daily Bugle, JJJ.";
		} else if (par == 33) {
			return "(#33) Today, in this insane war of ages across the multiverse has hit it's most tragic day. We aren't talking about bloodbathes, explosions or public bashing of victims, it's about betrayal. I know, I know, even before the day those demons came trough the portals, we already had traitors of freedom among us, but today we know that they were hiden in plain sight even on those who should be like a shield for us. SHIELD. The organization who would protect us for that level of threat, had hundreds of Hydra soldiers working with them, the same Hydra which almost nuked New York with a cosmic object, which now, thanks to the backport on the securities of the object, the cube, known as the Tesseract is in the hands of Hydra once again, and only God know what they will try to achieve this time. It may sound a hopeless future, but you my fellow citizen, must believe on our heroes. \u00A7o~Daily Bugle, JJJ.";
		} else if (par == 38) {
			return "(#38) Today, fellow american citizens, is a great day. Our heroes and brave soldiers have finally stopped the invasion from the WW2 hellish landscape of Earth-X after beating one of their great leader, Red Skull, who had in his hands the Tesseract. Little is known about the object origins, the fate of its owner, and how we will secure ourselves from future invasions like that, but, it's safe to say that atleast for today, our people will be able to inhale to their lungs the fresh air of freedom. The freedom of being safe, the freedom to live their own lifes once again, and the freedom of being who they truly are. \u00A7o~Daily Bugle, JJJ.";
		} else if (par == 39) {
			return "(#39) There already has been some hours since the end of the invasion and no authority, NO AUTHORITY, has spoken out about the terrors of outside and how they even got here, so, I, JJJ present to you, my own theory about the events of this so called Crisis, or should I say, Spidergeddon? Afterall, it's not the first time criminals of other worlds come down to this Earth thanks to the Spider-Foe, it's like he's some sort of totem to the disgraces of New York, and the disgraces of Earth. Scientists are trying to found solutions to seal those green and yellow or gray, black and red devils out of this Earth, I have a better solution, seal Spider-Man away from this Earth, and we will be safe. \u00A7o~Daily Bugle, JJJ.";
		} else if (par == 40) {
			return "(#40) Plastic-Man transfered to the Negative Zone after disguising himself as a inmate uniform at the laundry of the feminine block of Blackgate Prison. \u00A7o~Gotham Gazzete, unsigned.";
		} else if (par == 41) {
			return "(#41) Some frightened citizens of New York city claimed to see demons on dark alleys of the city. The phD Leonard Samson, says that it's just a case of mass hysteria. \u00A7o~Daily Bugle, Betty Brant";
		} else if (par == 42) {
			return "(#42) Multimillionaire Martin Li, become yesterday the majority shareholder of other two shelters in New York, he claims that FEAST was his first steps in the way of achieving a more fair and equal America. \u00A7o~Daily Bugle, Ned Leeds";
		} else if (par == 43) {
			return "(#43) Three young men have been arrested yesterday by trying to explode a bank with experimental technology while wearing chinese-style devil masks and blue tuxedos. All of them have claimed insanity and despite it's absurdity, the claims have been corroborated by most of the witnesses. Now, about their tech, specialist in nanotech, quantum physics, biological mechatronics \u00A7o~Daily Bugle, Betty Brant";
		} else if (par == 44) {
			return "(#44) Now to talk about the tech the three criminals, about their tech, specialist in nanotech, quantum physics, biological mechatronics and everything else that you can image, Melon Husk. \"Well, it's a clear case that they having been using stolen tech, since no one would ever be able to build that sort of technology in their garages\". Wait, but some of your friends have claimed that their empires were built... \"Delete that recording...\" \u00A7o~Daily Bugle, Ned Leeds";
		} else if (par == 45) {
			return "(#45) Fellow readers. We live in a free country. We are free to talk absolute anything that we want, but that's not give us the right to say our stupid toughts out loud. Still, after you said it, you said it and you shouldn't be able to not allow people to hear that, specially when you own half of the damn country! That's what we call censorship! But as I have been saying lately, this country justice is flawed, and now, the pig-face-heir of the emerald mines is trying to sue Daily Bugle! But stay calm fellow reader, we've got the truth, we can do what is right, we can make the justice work for us, the real people of this world, not these lizard-man-people! So, we, from the Daily Bugle, hundreds of workers ask for your understanding and yours charitable american citizen spirit, to donate to Daily Bugle fight back with all the people's might at the court. Stay strong citizens of this country, good always defeat evil. \u00A7o~Daily Bugle, JJJ";
		} else if (par == 46) {
			return "(#46) After some rampage on the FEAST shelter, the recent billionaire Martin Li was finally identified by the police to be the leader of the criminal gang known as the Inner Demons, a supervillain called Mr. Negative. The faction is composed of brainwashed people, wearing tuxedos and demon masks, they attack banks, civilians, and other buildings, after arrested, while still on the effect of the brainwashing, they all claim that the guilty of these acts is still to appear, due to his cowardness. But none of them actually said who the guilty is, policemen claimed that it's a good time to civilians stay at home and report anything suspicious. \u00A7o~Daily Bugle, Betty Brant";
		} else if (par == 47) {
			return "(#47) The billionaire Martin Li that turned out to be the terrorist known as Mr. Negative, lord of the Inner Demons, has been stopped by a hero on a fight, which resulted in the end of the brainwashing of the Inner Demons, letting free thousands, composed mostly of ex-convicts, ex-addicts, homeless and unemployed people, which all seeked for help in the shelters owned by Martin Li. The police and justice institutions are still debating on how to proceed with the case due to it's complexity, but for now, people can sleep safe, knowing their neighbors and friends have their conscience back. \u00A7o~Daily Bugle, Ned Leeds";
		}
		return "Nothing for today.";
	}
}
