package com.art5019.art5019s_injustice.helper;

import com.art5019.art5019s_injustice.data.Skill;
import com.art5019.art5019s_injustice.data.Skills;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.util.RandomSource;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import static com.art5019.art5019s_injustice.data.DataAttachments.*;
import static com.art5019.art5019s_injustice.data.Skills.INTELLIGENCE;

public class SkillHelper {

    /**
     *
     * @return Returns the cooldown/stress amount generated by the attempt to learn.
     */
    public static int learnSkill(Skills attemptedSkill, int sourceLevel, ServerPlayer player, int additionalHardness, ServerLevel serverLevel) {
        RandomSource randomSource = serverLevel.getRandom();
        int playerIntelligence = getIntelligenceLevel(player);
        int currentLevel = getProvidedSkillLevel(player, attemptedSkill);
        double baseChance = 0.31 - ((Math.pow(2,sourceLevel-currentLevel)/10F) + additionalHardness - playerIntelligence);
        if(randomSource.nextFloat() < baseChance) {
            attemptToUpgradeSkill(attemptedSkill,player);
        }
        return (int) (baseChance+ randomSource.nextFloat())*400;
    }

    public static int getIntelligenceLevel(ServerPlayer serverPlayer) {
        return getProvidedSkillLevel(serverPlayer, INTELLIGENCE);
    }

    public static int getProvidedSkillLevel(ServerPlayer serverPlayer, Skills skill) {
        List<Skill> skillList = serverPlayer.getData(SKILL);
        Optional<Skill> optionalSkill = skillList.stream().filter(x -> x.skillId() == skill.skillId).findFirst();
        return optionalSkill.map(Skill::skillId).orElse(0);
    }

    public static void removeSkill(Skills skill, ServerPlayer serverPlayer) {
        List<Skill> skillList = new ArrayList<>(serverPlayer.getData(SKILL));
        skillList.removeIf(x -> x.skillId() == skill.skillId);
        serverPlayer.setData(SKILL,skillList);
    }

    public static boolean attemptToUpgradeSkill(Skills attemptedSkil, ServerPlayer serverPlayer) {
        int currentLevel = getProvidedSkillLevel(serverPlayer, attemptedSkil);
        List<Skill> skills = new ArrayList<>(serverPlayer.getData(SKILL));
        if(attemptedSkil.levelCap > currentLevel) {
            removeSkill(attemptedSkil, serverPlayer);
            skills.add(new Skill(attemptedSkil.skillId, currentLevel+1));
            serverPlayer.setData(SKILL, skills);
            return true;
        }
        return false;
    }
}
