package com.art5019.art5019s_injustice.helper;

import com.art5019.art5019s_injustice.data.PlayerSkill;
import com.art5019.art5019s_injustice.data.Skill;
import com.art5019.art5019s_injustice.data.Skills;
import com.art5019.art5019s_injustice.network.SkillGainXpPacket;
import com.art5019.art5019s_injustice.network.SkillLevelUpPacket;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.components.toasts.Toast;
import net.minecraft.client.gui.components.toasts.ToastManager;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.util.RandomSource;

import java.util.*;

import static com.art5019.art5019s_injustice.data.DataAttachments.*;
import static com.art5019.art5019s_injustice.data.Skills.INTELLIGENCE;
import static java.util.Map.entry;

public class SkillHelper {
    public static int levelToXpFunction(int l) {
        return 500+125*((l*l)+3*l+2);
    }


    public static int getLevelForXp(int xp) {
        double level = (-375+Math.sqrt(135625 + 500*xp))/250;
        return (int) level;
    }

    public static int getPctOfNextLevel(int xp) {
        int currentLevel = getLevelForXp(xp);
        int nextLevel = currentLevel+1;
        int phaseXp = levelToXpFunction(currentLevel) - xp;
        int nextPhaseXp = levelToXpFunction(nextLevel) - levelToXpFunction(currentLevel);
        return (int) ((double) phaseXp / ((double) nextPhaseXp /100));
    }

    /**
     *
     * @return Returns the cooldown/stress amount generated by the attempt to learn.
     */
    public static int learnSkill(Skills attemptedSkill, int sourceLevel, ServerPlayer player, int additionalHardness, ServerLevel serverLevel) {
        RandomSource randomSource = serverLevel.getRandom();
        int playerIntelligence = getIntelligenceLevel(player);

        int currentLevel = getProvidedSkillLevel(player, attemptedSkill);

        if(currentLevel < sourceLevel) {
            player.playSound(SoundEvents.BOOK_PAGE_TURN,1,0.8F);
            player.giveExperiencePoints(randomSource.nextInt(0,4));

            int[] xps = addXpToSkill(player, attemptedSkill, randomSource.nextInt(20,70)+playerIntelligence*9);
            triggerToast(xps[0], xps[1], player, attemptedSkill.skillId);
            return (int) ((2-randomSource.nextFloat())*1800);
        }
        return 0;
    }

    public static int getIntelligenceLevel(ServerPlayer serverPlayer) {
        return getProvidedSkillLevel(serverPlayer, INTELLIGENCE);
    }

    public static void triggerToast(int oldXp, int newXp, ServerPlayer serverPlayer, int skillId) {
        int newLevel = getLevelForXp(newXp);
        if(newLevel > getLevelForXp(oldXp)) {
            serverPlayer.playSound(SoundEvents.PLAYER_LEVELUP,1,0.4F);
            serverPlayer.connection.send(new SkillLevelUpPacket(skillId, newLevel));
            return;
        }
        serverPlayer.connection.send(new SkillGainXpPacket(skillId, newXp));
    }


    public static int[] addXpToSkill(ServerPlayer serverPlayer, Skills skill, int xp) {
        List<PlayerSkill> skillList = new ArrayList<>(serverPlayer.getData(SKILL));
        Optional<PlayerSkill> optionalPlayerSkill = skillList.stream().filter(x -> x.skillId() == skill.skillId).findFirst();
        if(optionalPlayerSkill.isPresent()) {
            skillList.removeIf(x -> x.skillId() == skill.skillId);
            int oldXp = optionalPlayerSkill.get().xp();
            int newXp = oldXp+xp;
            skillList.add(new PlayerSkill(skill.skillId,newXp));
            serverPlayer.setData(SKILL,skillList);
            return new int[]{oldXp,newXp};
        }
        skillList.add(new PlayerSkill(skill.skillId,xp));
        serverPlayer.setData(SKILL,skillList);
        return new int[]{0,xp};
    }

    public static int getProvidedSkillLevel(ServerPlayer serverPlayer, Skills skill) {
        List<PlayerSkill> skillList = serverPlayer.getData(SKILL);
        Optional<PlayerSkill> optionalSkill = skillList.stream().filter(x -> x.skillId() == skill.skillId).findFirst();
        return optionalSkill.map(PlayerSkill::getLevel).orElse(0);
    }
}
