package com.art5019.art5019s_injustice.helper;

import com.art5019.art5019s_injustice.data.Skill;
import com.art5019.art5019s_injustice.data.Skills;
import com.art5019.art5019s_injustice.network.SkillLevelUpPacket;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.components.toasts.Toast;
import net.minecraft.client.gui.components.toasts.ToastManager;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.util.RandomSource;

import java.util.*;

import static com.art5019.art5019s_injustice.data.DataAttachments.*;
import static com.art5019.art5019s_injustice.data.Skills.INTELLIGENCE;
import static java.util.Map.entry;

public class SkillHelper {
    public static int levelToXpFunction(int l) {
        return 500+125*((l*l)+3*l+2);
    }


    public static int getLevelForXp(int xp) {
        double level = (-375+Math.sqrt(135625 + 500*xp))/250;
        return (int) level;
    }

    /**
     *
     * @return Returns the cooldown/stress amount generated by the attempt to learn.
     */
    public static int learnSkill(Skills attemptedSkill, int sourceLevel, ServerPlayer player, int additionalHardness, ServerLevel serverLevel) {
        RandomSource randomSource = serverLevel.getRandom();
        int playerIntelligence = getIntelligenceLevel(player);
        int currentLevel = getProvidedSkillLevel(player, attemptedSkill);
        if(currentLevel < sourceLevel) {
            player.playSound(SoundEvents.BOOK_PAGE_TURN,1,0.8F);
            player.giveExperiencePoints(randomSource.nextInt(0,4));
            double baseChance = Math.pow(1,sourceLevel-currentLevel) - additionalHardness + (double) playerIntelligence /100;
            if(randomSource.nextFloat() < baseChance) {
                attemptToUpgradeSkill(attemptedSkill,player, serverLevel);
            }
            return (int) ((1-baseChance)*4000);
        }
        return 0;
    }

    public static int getIntelligenceLevel(ServerPlayer serverPlayer) {
        return getProvidedSkillLevel(serverPlayer, INTELLIGENCE);
    }

    public static int getProvidedSkillLevel(ServerPlayer serverPlayer, Skills skill) {
        List<Skill> skillList = serverPlayer.getData(SKILL);
        Optional<Skill> optionalSkill = skillList.stream().filter(x -> x.skillId() == skill.skillId).findFirst();
        return optionalSkill.map(Skill::level).orElse(0);
    }

    public static void removeSkill(Skills skill, ServerPlayer serverPlayer) {
        List<Skill> skillList = new ArrayList<>(serverPlayer.getData(SKILL));
        skillList.removeIf(x -> x.skillId() == skill.skillId);
        serverPlayer.setData(SKILL,skillList);
    }

    public static boolean attemptToUpgradeSkill(Skills attemptedSkill, ServerPlayer serverPlayer, ServerLevel serverLevel) {
        int currentLevel = getProvidedSkillLevel(serverPlayer, attemptedSkill);
        if(attemptedSkill.levelCap > currentLevel) {
            serverPlayer.playSound(SoundEvents.PLAYER_LEVELUP,1,0.4F);
            removeSkill(attemptedSkill, serverPlayer);

            List<Skill> skills = new ArrayList<>(serverPlayer.getData(SKILL));

            Skill leveledUpSkill = new Skill(attemptedSkill.skillId, ++currentLevel);
            skills.add(leveledUpSkill);
            serverPlayer.setData(SKILL, skills);
            serverPlayer.connection.send(new SkillLevelUpPacket(leveledUpSkill.skillId(),currentLevel));
            return true;
        }
        return false;
    }

    public static void showSkillToast(ServerPlayer serverPlayer) {
        //Minecraft.getInstance().gui.toastManager().addToast();
    }
}
